/* Drop Triggers */

DROP TRIGGER TRI_JOB_HISTORY_HIS_NO;
DROP TRIGGER TRI_POSITION_PNO;
DROP TRIGGER TRI_REVIEW_REVIEW_NO;
DROP TRIGGER TRI_SALARY_PAYMENT_SALPAY_NO;
DROP TRIGGER TRI_YEARS_YEARS_NO;

/* Drop Tables */

DROP TABLE JOB_HISTORY CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE SALARY_INFO CASCADE CONSTRAINTS;
DROP TABLE SALARY_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE WORK CASCADE CONSTRAINTS;
DROP TABLE YEARS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE HR_SYSTEM CASCADE CONSTRAINTS;
DROP TABLE SALARY_STEP CASCADE CONSTRAINTS;
DROP TABLE POSITION CASCADE CONSTRAINTS;

/* Drop Sequences */

DROP SEQUENCE SEQ_JOB_HISTORY_HIS_NO;
DROP SEQUENCE SEQ_POSITION_PNO;
DROP SEQUENCE SEQ_REVIEW_REVIEW_NO;
DROP SEQUENCE SEQ_SALARY_PAYMENT_SALPAY_NO;
DROP SEQUENCE SEQ_YEARS_YEARS_NO;